import os
a='\\\\abr-nas2.cisco.com\\scratch\\Wei\\'
fileName = "test.ism"

def webgen(a,filename):
    fileWebPage = open(fileName+".html",'w')
    fileWebPage.writelines("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n")
    fileWebPage.writelines("<html xmlns=\"http://www.w3.org/1999/xhtml\" >\n")
    fileWebPage.writelines("\n")
    fileWebPage.writelines("<head>\n")
    fileWebPage.writelines("    <title>Smooth Streaming Player</title>\n")
    fileWebPage.writelines("    <style type=\"text/css\">\n")
    fileWebPage.writelines("    html, body {\n")
    fileWebPage.writelines("        height: 100%;\n")
    fileWebPage.writelines("        overflow: auto;\n")
    fileWebPage.writelines("    }\n")
    fileWebPage.writelines("    body {\n")
    fileWebPage.writelines("        padding: 0;\n")
    fileWebPage.writelines("        margin: 0;\n")
    fileWebPage.writelines("    }\n")
    fileWebPage.writelines("    #silverlightControlHost {\n")
    fileWebPage.writelines("        height: 100%;\n")
    fileWebPage.writelines("        text-align:center;\n")
    fileWebPage.writelines("    }\n")
    fileWebPage.writelines("    </style>\n")
    fileWebPage.writelines("    <script type=\"text/javascript\">\n")
    fileWebPage.writelines("        function onSilverlightError(sender, args) {\n")
    fileWebPage.writelines("            var appSource = \"\";\n")
    fileWebPage.writelines("            if (sender != null && sender != 0) {\n")
    fileWebPage.writelines("              appSource = sender.getHost().Source;\n")
    fileWebPage.writelines("            }\n")
    fileWebPage.writelines("\n")
    fileWebPage.writelines("            var errorType = args.ErrorType;\n")
    fileWebPage.writelines("            var iErrorCode = args.ErrorCode;\n")
    fileWebPage.writelines("\n")
    fileWebPage.writelines("            if (errorType == \"ImageError\" || errorType == \"MediaError\") {\n")
    fileWebPage.writelines("              return;\n")
    fileWebPage.writelines("            }\n")
    fileWebPage.writelines("\n")
    fileWebPage.writelines("            var errMsg = \"Unhandled Error in Silverlight Application \" +  appSource + \"\\n\" ;\n")
    fileWebPage.writelines("")
    fileWebPage.writelines("            errMsg += \"Code: \"+ iErrorCode + \"    \\n\";\n")
    fileWebPage.writelines("            errMsg += \"Category: \" + errorType + \"       \\n\";\n")
    fileWebPage.writelines("            errMsg += \"Message: \" + args.ErrorMessage + \"     \\n\";\n")
    fileWebPage.writelines("\n")
    fileWebPage.writelines("            if (errorType == \"ParserError\") {\n")
    fileWebPage.writelines("                errMsg += \"File: \" + args.xamlFile + \"     \\n\";\n")
    fileWebPage.writelines("                errMsg += \"Line: \" + args.lineNumber + \"     \\n\";\n")
    fileWebPage.writelines("                errMsg += \"Position: \" + args.charPosition + \"     \\n\";\n")
    fileWebPage.writelines("            }\n")
    fileWebPage.writelines("            else if (errorType == \"RuntimeError\") {  \n")
    fileWebPage.writelines("                if (args.lineNumber != 0) {\n")
    fileWebPage.writelines("                    errMsg += \"Line: \" + args.lineNumber + \"     \\n\";\n")
    fileWebPage.writelines("                    errMsg += \"Position: \" +  args.charPosition + \"     \\n\";\n")
    fileWebPage.writelines("                }\n")
    fileWebPage.writelines("                errMsg += \"MethodName: \" + args.methodName + \"     \\n\";\n")
    fileWebPage.writelines("            }")
    fileWebPage.writelines("\n")
    fileWebPage.writelines("            throw new Error(errMsg);\n")
    fileWebPage.writelines("        }\n")
    fileWebPage.writelines("    </script>\n")
    fileWebPage.writelines("</head>\n")
    fileWebPage.writelines("<body>\n")
    fileWebPage.writelines("    <form id=\"form1\" runat=\"server\" style=\"height:100%\">\n")
    fileWebPage.writelines("    <div id=\"silverlightControlHost\">\n")
    fileWebPage.writelines("        <object data=\"data:application/x-silverlight-2,\" type=\"application/x-silverlight-2\" width=\"100%\" height=\"100%\">\n")
    fileWebPage.writelines("          <param name=\"source\" value=\"vplayer_latest.xap\"/>\n")
    fileWebPage.writelines("          <param name=\"onError\" value=\"onSilverlightError\" />\n")
    fileWebPage.writelines("          <param name=\"background\" value=\"white\" />\n")
    fileWebPage.writelines("          <param name=\"minRuntimeVersion\" value=\"4.0.50401.0\" />\n")
    fileWebPage.writelines("          <param name=\"autoUpgrade\" value=\"true\" />\n")
    fileWebPage.writelines("          <param name=\"enableGPUAcceleration\" value=\"true\" />\n")
    fileWebPage.writelines("                  <param name=\"InitParams\" value=\"IsStartPositionOffset=false,AutoPlay=true,mediaurl="+a+fileName+"/manifest\" />\n")
    fileWebPage.writelines("          <a href=\"http://go.microsoft.com/fwlink/?LinkID=149156&v=4.0.50401.0\" style=\"text-decoration:none\">\n")
    fileWebPage.writelines("               <img src=\"http://go.microsoft.com/fwlink/?LinkId=161376\" alt=\"Get Microsoft Silverlight\" style=\"border-style:none\"/>\n")
    fileWebPage.writelines("          </a>\n")
    fileWebPage.writelines("        </object><iframe id=\"_sl_historyFrame\" style=\"visibility:hidden;height:0px;width:0px;border:0px\"></iframe></div>\n")
    fileWebPage.writelines("    </form>\n")
    fileWebPage.writelines("</body>\n")
    fileWebPage.writelines("</html>\n")
    fileWebPage.writelines("\n")
    fileWebPage.close()
    
webgen(a,fileName)